baseURL:                "https://jamesm.blog/"
buildDrafts:            false
buildExpired:           false
buildFuture:            false
enableEmoji:            true
enableInlineShortcodes: true
enableRobotsTXT:        true
#googleAnalytics:        UA-123-45
pagination.pagerSize:   5
pygmentsUseClasses:     true
title:                  jamesm.blog

# Theme
# Others: ananke beautifulhugo hugo-book hugo-devresume-theme hugo-paper hugo-PaperMod hugo-theme-stack LoveIt m10c terminal
#theme: hugo-theme-stack
#theme: hugo-PaperMod
theme: hugo-PaperModX

minify:
  disableXML:    true
  #minifyOutput: true

languages:
  en:
    languageName: "English"
    weight:       1
    taxonomies:
      category: categories
      tag:      tags
      series:   series
    menu:
      main:
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10
        - name: AI
          url: /ai
        - name: Blockchain
          url: /blockchain
        - name: Data
          url: /data-engineering
        - name: DevOps
          url: /devops
        - name: General
          url: /general
        - name: Music Production
          url: /music-production
        - name: Personal Dev
          url: /personal-development
        - name: Space
          url: /space

outputs:
  home:
    - HTML
    - JSON
    - RSS

params:
  author:                 James M
  #comments:              false
  env:                    production
  #description:           "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
  defaultTheme:           auto
  #disableSpecial1stPost: true
  #disableThemeToggle:    true
  displayFullLangName:    true
  images:                 ["papermod-cover.png"]
  mainSections: 
    - ai
    - blockchain
    - data-engineering
    - devops
    - general
    - music-production
    - personal-development
    - space
  ShowCodeCopyButtons:            true
  ShowBreadCrumbs:                true
  ShowPostNavLinks:               true
  ShowReadingTime:                true
  ShowRssButtonInSectionTermList: true
  ShowShareButtons:               true
  ShowToc:                        true

  profileMode:
    enabled:      false
    title:        PaperMod
    imageUrl:     "#"
    imageTitle:   my image
    #imageWidth:  120
    #imageHeight: 120
    buttons:
      - name: Archives
        url:  archives
      - name: Tags
        url:  tags

  homeInfoParams:
    #Title: "James' Blog"
    Content: |
      Welcome to my blog, the following topics are covered here;
      - [**Artificial Intelligence**](/ai) (chatbots, co-pilots, LLMs, robotics)
      - [**Blockchain**](/blockchain) (Bitcoin, Blockchain, decentralization, Polkadot)
      - [**Data Engineering**](/data-engineering) (databases, ETL, Data Science, ML)
      - [**DevOps**](/devops) (automation, AWS, CI/CD, Cloud, Docker, IaC, K8s)
      - [**General**](/general) (general topics & news)
      - [**Music Production**](/music-production) (computer hardware & software)
      - [**Personal Development**](/personal-development) (books, courses)
      - [**Space**](/space) (exploration, rockets)

  socialIcons:
    - name: gmail
      url: "mailto:jamesmyddelton@gmail.com"
    - name: linkedin
      url: "https://uk.linkedin.com/in/jamesmyddelton/"
    - name: twitter
      url: "https://twitter.com/jamesmyddelton/"
    - name: facebook
      url: "https://www.facebook.com/jamesmyddelton/"
    - name: instagram
      url: "https://www.instagram.com/jamesmyddelton/"
    - name: youtube
      url: "https://www.youtube.com/@JamesMyddelton/playlists/"
    - name: telegram
      url:  "https://t.me/jamesmyd"
    - name: soundcloud
      url: "https://soundcloud.com/jamesm/"
    - name: github
      url: "https://github.com/jmydde/jamesm.blog"
    - name: KoFi
      url: "https://ko-fi.com/U6U1LGXXV/"
    - name: tiktok
      url:  "https://www.tiktok.com/@james.m.uk"
    - name: other
      url: "https://ClubTheWorld.uk"
    - name: other
      url: "https://DevOpsForum.uk"
    - name: other
      url: "https://tensor.art/u/855380090597470967"
    - name: rss-simple
      url: "index.xml"

  # editPost:
  #     URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
  #     Text: "Suggest Changes" # edit text
  #     appendFilePath: true # to append file path to Edit link

  # label:
  #     text: "Home"
  #     icon: icon.png
  #     iconHeight: 35

  # analytics:
  #     google:
  #         SiteVerificationTag: "XYZabc"

  assets:
      disableHLJS:  true
      #favicon:      "/favicon.ico"
      #favicon16x16: "/favicon.ico"
      #favicon32x32: "/favicon.ico"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     keys: ["title", "permalink", "summary", "content"]

  # m10c Default theme
# style:
#   darkestColor: "#242930"
#   darkColor: "#353b43"
#   lightColor: "#afbac4"
#   lightestColor: "#ffffff"
#   #primaryColor: "#57cc8a"
#   primaryColor: "#57bacc"
#   #primaryColor: "#575dcc"

  # m10c Green theme
# style:
#   darkestColor: "#315659"
#   darkColor: "#253031"
#   lightColor: "#96a879"
#   lightestColor: "#fff"
#   primaryColor: "#dad865"

  # m10c Red theme
# style:
#   darkestColor: "#d35050"
#   darkColor: "#212121"
#   lightColor: "#f5e3e0"
#   lightestColor: "#f5f5f5"
#   primaryColor:  "#ffffff"

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses:      false
    #anchorLineNos: true
    #codeFences:    true
    #guessSyntax:   true
    #lineNos:       true
    #style:         monokai

privacy:
  vimeo:
    disabled: false
    simple:   true

  twitter:
    disabled:  false
    enableDNT: true
    simple:    false

  instagram:
    disabled: false
    simple:   true

  youtube:
    disabled:        false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
